language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t yojimat/frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true yojimat/frontend npm run test

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: dockerkubernetesdemo